---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-l2tp-bridge-secret
  namespace: tailscale-l2tp-bridge
spec:
  encryptedData:
    IPSEC_PSK: AgCYbKcoZ6y9Xi7NnmgRDKzBGbVKsTSLUyNXBWHE9JkW4YEKy1s4hKboo9gObIiW75welbjGcX38GtwQNPH+cIJEZsbxGrFd0DEi197FPybJwkkTjQEIMgq6WzydHkhKx7MYyUX9AGx83LbtAKbQyoEk0/INrZvvEyKaSUHcaSLUnWief8yFxs2vDRZvNRIekDBWy34TGUUF//jS5XtMtZoQO/FO23iIVKxRgO6YJbHKmoBP2jpuajdBbjQRDDuxwIOI+iHueGO9lmpY3oURw0PiFyZJji23w2sHIgsca98ohQRNgWx2Xe90SoVKAy5fSW4NjPkQ3v9r0Va67I1zfbiK81vPyBlyyyuQG46Na2S41X199Iimu+uctru5oe8du8cNYqX34n4YrnCbyznJ8izg029kaFAKD5ze3CNwn4RRZ0PePeIZg+zE8EVsBI1FC3caXSEQt9LWbECfVUR+aQqRGe0JcPv2FLVwNR6rdpi719R6hQ3pL/QWRGQK1dHM7lMtGnSRs6lyS2gSN62makIAGgs7D+7jHboGMWi3vO/0/bKo8eFun3qQEGutbJVsbCG0gdcCCX3oJhddaOaOT/bRTdnxIDAfFKunag0OSqhmcNdPl/gLMzIAwx46SjytE+5OL5h9zS/cq3CnUyOAgC2zwPjBNEYe1xEW/0wuSaHjlWmlhLCuABpG2Op55EMnbKOdjrUyc45fnGiGj/Rx9Z+2tENPh/iEWd/Drs6kNK+PLQ==
    L2TP_PASSWORD: AgB54zMvSOlweG5QL9eCFNJRwNTMsr0mMDaE6lNGDn8lUjaIenwP7Fk5xQhWlzTnEcKoxR884w147NurJrc2UbLKI4Nn48TlWRWWbOY4wkAbsk2A/hfFyaXzYWzQN7W9wn0zhsiDvAG601Wpd7zdTyJNdjAfvaMTIA16vRI1XyiQ3gHsKTeZW03xIQMHRIh+OaCEymhTJ3jHLbL03j54NmscIP+oadWE8d6Pc3PPgXBUE19H5jqlbSSP81ubBRXLwHK435Vwgkia9pTfyH7FtxJzmPcXvD0WEbzg0nAPfRS2sWkgAiVPMljFa4vs7NEEYtOh1iu0f5ry79h/n7p1+IBn58vArCfhED7tWPWLobRiDPogPEn/91nQtEhIBy/7liO2HywRr4cLoXOJ1d+YqdvfuiXTq+eqkyBg0iCGbO5ihK50glDqq2X9Jk6p0SBWQ97wZZj0yLaUDmpEoXXBBuXX+5AKeOPxsz+ymP2yUBf7LHc7ZvqvtF4tIs1b3oXzR2FSQuMWModVsg2hAljkZfwL2VCqpcnSzvllK2/9Mfzu3v9RkVqvaSnG//+iz+1WGwV6j73H5xcqRAfEYHbLxtZJjZgjyLhuu2YvOOhn6T7yHaJSAy1Ak89JICynNlT0K1LrQgZWNBASUYo1gmBNQY1tNL/CPi6Fj1392A3jol64nP9hBlnA03uL04bo/ZUX2v+3XM5nPtqCvhitusSTiDyeJgCUpQ==
  template:
    metadata:
      name: tailscale-l2tp-bridge-secret
      namespace: tailscale-l2tp-bridge
    type: Opaque
