---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-l2tp-bridge-secret
  namespace: tailscale-l2tp-bridge
spec:
  encryptedData:
    TS_AUTHKEY: AgCXO2WYDuNl1M/aHVoByXI+1FiQW1hHQaQuZmW3Cw/J/tg1D//ziCemOLo+U6nidT3BRjx9zWTyRLteOrvow/9HoEPQDKhwSdSDDO96WvLl/t9bqYBShw0EjnCLDGZHtAm3a+h1uIkWteRw37n7Q4kbM0Jjk+hkq0m0D23vFVAXyJpNRqGhes43zTsAWQKWfNf48EaMiKyePm86uPVmZhCWAoAox/T9QGJKTV5TVcb+cQ6W+wlz3ySL2VQVG6XqG9SaFc1eO2YqvCAg0VfSZ7346MIoWroYWj9RKhNvAQyK7RoTaWdgoGeL+2LT98LZNIW06+U+pp/xqxEJphTsYk/YU2qL8bXuUhUlOOvUNNxLaPABZ4pw7CV/ylQ2UPzSF7Ft8yS3d9d2deOG9KxWBJ9e0xcIsCAQbeTM5XIoMRyLLZuRZJ5tAOt50zM1Hr9qH/5LOj5fxgC3bzUk0Vz1k6muGaRSSON88wMIhGajvp0cp8zcyV7XMDLJ4p0tVUdpB64wVHwK/zMdrLR8NFmv9WaT16naTmYDaW6xipcXaqA0mfA+FsHo6Luu2SN9wDe1iKPq8ORmMUJ7397lDPcc+vM58NcPhIpPNWU5Pgl/FKA3qCdEaMBHhgjg1gmKRGpW9VRR7CBN33YkeF6MkDI1DbWKzcUOcOejC036iYrLoEz+UZIV2WezxJ5wfJqPVcRfWunt3m66bNFksKDGG1hMvy7fDkgPMvP5nCfEz2PDqcoJJEQ8SBN3S/vuEunlxO72jB1Y7AGLtsQfK76WEGZW
  template:
    metadata:
      name: tailscale-l2tp-bridge-secret
      namespace: tailscale-l2tp-bridge
