---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-l2tp-bridge-tailscale
  namespace: tailscale-l2tp-bridge
spec:
  encryptedData:
    TS_AUTHKEY: AgCNHiGs1vh4ylVs/wdWFXjI04mQmFn349/H+VSfYnqLxIthH5jYpB7C/FhbggvY5syENGD3NgcBeCsdR8kHcKOPByE8PfQWEfC1+FqJxFQylDEw/mKC88LkMycANOwPNF+oLouJjISixe/u2qb325E6aIIt2u340c2G/xZ6+Cw7f5ZL4Dn6IDUhs7jGeDLI3O5BaDEccApHMWzfoKmSSrOLrkmH54UzLnRDGLMiKAlmY5cVp4vM8zDybci0MTy0eVZ1dXZo56k/ElBs/vubcm6U3jtScxS3PrLuPhcJmDjk9747v9rPpWpEkRJ3b3BMnAK7shVYP8GBhL9wY0L+rR7YbHoRICbLPGUEEE19QuPO0kIvn19skO5djeLbB+6/QPYozI1PU+CMgSNkuxZ3qVHSaLiIAQnKTyzG4W656+rALSRNfjDRnWbN3NKSdRrjZATQ6E5uGVIRYAPqoZqYWcBbtS7hzAN78gA7598JNayXv4Jzxm9+C/XB6vCZhLvBT5MW/senCvEov5DEzVbrw1Yq9D3xsq77lhx4nDR3d1RGq6vI0jgoNR7MAnd7HFS5oyYKM1WTxGuOLMUTo7HN1DNucCjILjpfSiIyfIpkenSWS9r2kBVx0pCfarwdMM9qXIiqh73U7wfxPBw9+8AShYYIP+NFLDVvBaS/BlJ07MUUbQa+/GVoQ66cQ1dZd+a/jkuBhqGZ97Xc909g0AjGcvm+VU4WsX0D4IseJi29Frneh6TdHqdgssN5OBXNfif1W/BSQ8QRqfz4roc7qMIk
  template:
    metadata:
      name: tailscale-l2tp-bridge-tailscale
      namespace: tailscale-l2tp-bridge
