---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-l2tp-bridge-tailscale
  namespace: tailscale-l2tp-bridge
spec:
  encryptedData:
    TS_AUTHKEY: AgCViYxDgIY8BoQxsVF0oPajKJLwEiCgE1UN1vl4jBNhh4CPZ6+zJknGyb/vV0ncrE5K6Aly/B7ugIrjpH6T0/XoryxhXrHl+mSTTPV4SrIyJapxB4SE8QYnSM6/uq+0H5gasuLd+j8kZEoMx3vetYmhVLVpRmVmouP1JxIQVSiyoUkLoPSXcvh6Fpij5X0f36yi4Z1n2mdAlWAsARfK6KK4/bR7HaQHdbFVHvCdHWlGOBj1eomvL6bYzsyfpLqo7tyfUPgC18qxl0Q12A7c9yGiwkoFYtkf/EmGjSGVbrGHHgS89vmSwtJPXwozMkLRVOHUh3KGkFPc+1cdDdWaO68DaSsYw9Ts4/aQzu7McQG3LRB5raexIYqZDiJk03wWSU9sqOBeXSbyTKtdE/U3y3SvhMmjSNNDVWya6DrBGvyNvERlzNr9jHlq4qKugPo65DJllJr2lLtctsrmUtrDwEfM6ZqWoFEpj3JoSbpMUlAq6kivWd5da5/o9rkJkJSWpYWTWQdSiE65+eYQaTadl1RX2fp6eZrgeXvY5VV/0Hv19cZmfpG14Geafi9c7zrK8Z0PI4lbi/QNL1Oeuug9reeIWZgYAjo/tiSVkRf5Zay/HVzOx4AIHtOephlvA5wJIwLCJ3mZ0R8cSc5EdK1vk7J+QpXPuWqUbbCwRMvA233s58KcBB6r55lUEbn0EqIbkFB9lTe5DSKkSsd88DYRorpDuu/vzikGnkZBupHsdTuIwGHqCLL1v+1YYtTyOTcDmvRSQW3lzqJBKCETxGyY
  template:
    metadata:
      name: tailscale-l2tp-bridge-tailscale
      namespace: tailscale-l2tp-bridge
