apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    logs:
      access:
        enabled: true
    ports:
      web:
        hostPort: 80
      websecure:
        hostPort: 443
    service:
      spec:
        type: ClusterIP
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 0
    providers:
      kubernetesIngress:
        publishedService:
          enabled: false
        ingressEndpoint:
          hostname: "cloudarm.arec.me"