apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    hostNetwork: true
    ports:
      web:
        port: 80
      websecure:
        port: 443
    securityContext:
      capabilities:
        drop: []
        add: [NET_BIND_SERVICE]
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    podSecurityContext:
      runAsNonRoot: false
      runAsUser: 0
      runAsGroup: 0
    service:
      spec:
        type: ClusterIP
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 0
    providers:
      kubernetesIngress:
        publishedService:
          enabled: false
        ingressEndpoint:
          hostname: "cloudarm.arec.me"