---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-l2tp-bridge-netbird
  namespace: netbird-l2tp-bridge
spec:
  encryptedData:
    NB_SETUP_KEY: AgBC+Pw9w1zwz7IabSfxS92HnaTGZskuHzctrr+rDD/Nd3pixl4Yokm7mah/V1aCQ6n6MzPul+QIgvZDp/9dw2dS3d3M90ebC5mNccp+NQEuZSZVTz+ckgEHa2FMUbzVDU63G9hIhGgLQO5STt2u3YV7cioEGK0TnL6cE/1nyEyn0/0RaX5fWG70rrdUPOhWwKj+TfQNJARNGzGwXl5qWsvUeWd4s1yVBCqarJCd8R09EQ4ut88jYikCeR+fahf8khVewWGTT2V1r9FFX8sy0j3AgUZfX0IDkjlwnx43RcRw3l9GXo2BDLZYZfJjmmx6DUGRfEk2D6vvb6HgOoNYkR81ktcuMv+forBqBnTfmWlmJT22k1uos0SW8eqWO0dytbyO8c1CJNdp+kJ/4ddwY1Hj6ggSxKl+FeBD4zg40BKcnG72x+VFG2eQ8N5O7Apu3GVzpJl/Nqs0yk5XWypStQ4qNQi3DYppqDE1XDz+3Cp1O8OVZyE7UuL9hR3L0iS0mxzV1S2AVz7XyyQs0WefwlCcjZpzuxJjof9pyWfCb7D53/9u4QClCsW3fNzePZhzZZYNNYx435IgmfFgTQvxeI9F7pyyA/MjW8KA95h9DHyfvBA/eQlsAsnGFEekLOGSyaqlpCqEcZgOCYmN8Euuzq7t63Iruc7fMN5mnL572mOY0MHz1fz0fW4qtjUPr3xAM2Ntzd3dKqUxDwMqdSxuuUd7p9TgfKK+83Gk3UPtv689y0HUdco=
  template:
    metadata:
      name: netbird-l2tp-bridge-netbird
      namespace: netbird-l2tp-bridge
