---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-l2tp-bridge-secret
  namespace: netbird-l2tp-bridge
spec:
  encryptedData:
    IPSEC_PSK: AgCKgaXFGgk2uY6t1nEd+pmMAgNaDRBeoX+vVMbGBuRh9oKhVoQDJs1Lv8UU6xBpmOWe+IDXlR4kMlCLcwMXPMiGTc2u0gKVjNuwqUM9qCaNgEc5Cd5ZITY0DdR8QUgfN3QYLNDxiGi1D2JaL+PN9LnoMsR0XyJTXF+0EsplJSkHr8j8LIpaso9uQ7q1UqU5Aef59GHw4WszG9kkgopxdNGMQkuUHg5QW1s2RJrIenuNIJM3MBLfSTCgIX54ZnpsrS8qmUQp/FJ4EloawZOMCq8EbLGlbYBn2hE3LE97hrxzH3FLW22w2saBDjgl4MLs818GJougWYqsRRHTFyTHGFJ8OKjEo6cau6NW7duiRtzj5cAN5SV22IpKtjRsEQh0A+CrSYdCqUk8qlQHPUFEeExauFDUX3gUaciw3iMOnrVl89YphlvIMnwLXOSZy7EcyvD5IF0GRqIGXYouMYR5a8KCLFQGZ8jSuIbpNo6wK/Rx+cTuwgP283TIgx+G18s61epl8hdVcg26I7Cl+YfAUSE2iWSmLdXJctiY4GlVcy9zzGtGBt1puNEsQcrbPCM8mqB3NoKrdGlkWeSjqmJQ9dVLjdcoDgHyrXzfwS6URiW4eRHynWgBp5/n+F5PWa8r0npg3LR+GSsdte8KyHcLRcRcRp3+mA3ihyQvffqMKYfw/jrycQPICI/KjDV/nDIUoFbHgk2jcn/YfluBPFth+MwOUtsubEI0UMeh91tWtiw8ag==
    L2TP_PASSWORD: AgBKNqVKsqmNiBiqhCtqG6JxaOK3AzLgyH1LNQ6kCF4iu0Cek55u9+wDOF9avRy9+kq8IsDbXFGrdky0HlLC+HTPdVnPWX4iY9WUesLA+RxTnUxt8cWIFbRS8Dr9fqMkrWJA5iRmD5ZgiIZloJS6RE3EhKbKirh5FeNXE/vplPF3wlV+hD23T2Jn4uxYT2Pa1zLLVOAsxcx+GtVpyjChfkX1I3ZLwqWXs+d0OKdE0ZucH6CoATR5+zcbW8h5EFT5iVJtvGU2e3JrAkfKRUn/oOuO/l5Vnmgbn6b76AJdXWvXeIzQcHHdq7Sh93Yue57SNevTsNiS2cjSXIanx68tWgH27b83ZhZ6ZYQf4+IWvnFhvjVe3VRMsGlUOqlGXnWOO9Pf6d83nVbEK7wP12RJf6lfoV5Q26qAHII/HZzK8oFiH+qMQRQGTg3TME+0/JT4nvp7B0e2V0vC9GWXjtGvWpVucqiD/0mb7IM7Adn+hvK3r2ZS2tz479+5IPX9fdQam9lCD7w/hjd+rIfc8LjUQBixQ7aSR3IBQdz0/lUgv/IEkVU+3oQIzbSLV6Icik/+ED06IaTi3YR77cI5qXqz3rV7f6D/t+cOWOvFEqQz4i9gL/2/lxJxABgyekP6KrsCr0wf/5JmuYZQ1+odBLKqezSXW7sx/JktuC63MRrGFpQA2X372NN85fHgbiVVmvltxaeAfE9KGqKR3ff7PTgTp4/ySrL7oQ==
  template:
    metadata:
      name: netbird-l2tp-bridge-secret
      namespace: netbird-l2tp-bridge
